### ISSUE TITLE
Standin for quantities until MAB is ready for deployment

### ISSUE THREAD

**Issue by alansaviolobo** [TechnoPunter/trade-exec-engine#4]
Purchase quantities are to be hardcoded until Multi Arm Bandit Strategy is ready for deployment

**Comment by pra1had** [comment]
Do we need a filter for PNL > 0 for quantity allocation?


<img width="818" alt="image" src="https://github.com/TechnoPunter/trade-exec-engine/assets/115211965/b9c382cf-7770-4dcf-b2a7-38e99e8e2bff">

**Comment by alansaviolobo** [comment]
If you put the filter then what is the quantity in case the script is not
in your list?

**Comment by pra1had** [comment]
Didn't understand your point - call?

**Comment by pra1had** [comment]
https://docs.google.com/spreadsheets/d/12IVO9hZXZjGtNUhjSfLHRZlaCFqzSmyZ/edit#gid=1536044396
Using the Final Output sheet from the document to generate entries. 

<img width="930" alt="image" src="https://github.com/TechnoPunter/trade-exec-engine/assets/115211965/fd73ea0d-1184-4806-beea-604b8e471e23">
Matching:
<img width="641" alt="image" src="https://github.com/TechnoPunter/trade-exec-engine/assets/115211965/3386e0ed-715e-4539-a3b6-6baa8a57ccb0">

**Comment by pra1had** [comment]
Done
